Finn 2
mamc3334/18272-Project pull request #35
Opened 2024-11-11 10:17 UTC by fbuggy

2024-11-11 11:09 UTC, mamc3334 requested changes
Needs changes

2024-11-12 18:18 UTC, mamc3334 requested changes
Merge in main and repush.

2024-11-14 09:20 UTC, mamc3334 commented on common/utility.hpp
> +        return (r == other.r && g == other.g && b == other.b);
resolve merge conflict

2024-11-14 09:20 UTC, mamc3334 commented on common/utility.hpp
> +=======
resolve merge conflict

2024-11-14 09:21 UTC, mamc3334 commented on imgaos/CMakeLists.txt
> +        PUBLIC
what does this do?

2024-11-14 09:43 UTC, mamc3334 commented on imgaos/CMakeLists.txt
> +        ${CMAKE_CURRENT_SOURCE_DIR}
What does this target_include ... do?

2024-11-14 11:03 UTC, mamc3334 approved these changes

2024-11-14 11:06 UTC, 100496948 approved these changes

2024-11-14 11:06 UTC, merged